version: '3.1'

# https://github.com/docker/awesome-compose/blob/master/sparkjava-mysql/compose.yaml
services:
  mysql:
    image: mysql:latest
    container_name: oc_rentals_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: oc_rental
