openapi: 3.0.2
info:
  title: Rental OC API
  description: API to manage rental locations and user authentication
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: Authentication
    description: Operations related to user authentication and registration
  - name: Rentals
    description: Operations related to rental management

paths:
  # Authentication endpoints
  /auth/register:
    $ref: './openapi/paths/auth.yaml#/register'
  /auth/login:
    $ref: './openapi/paths/auth.yaml#/login'
  /auth/me:
    $ref: './openapi/paths/auth.yaml#/me'

  # Rental endpoints
  /rentals:
    $ref: './openapi/paths/rentals.yaml#/collection'
  /rentals/{id}:
    $ref: './openapi/paths/rentals.yaml#/item'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Use the JWT token obtained from login or registration."

  schemas:
    # Request schemas
    RegisterRequest:
      $ref: './openapi/schemas/requests/RegisterRequest.yaml'
    LoginRequest:
      $ref: './openapi/schemas/requests/LoginRequest.yaml'
    RentalRequest:
      $ref: './openapi/schemas/requests/RentalRequest.yaml'

    # Response schemas
    AuthResponse:
      $ref: './openapi/schemas/responses/AuthResponse.yaml'
    RentalResponse:
      $ref: './openapi/schemas/responses/RentalResponse.yaml'
    RentalsResponse:
      $ref: './openapi/schemas/responses/RentalsResponse.yaml'

    # DTO schemas
    RentalDto:
      $ref: './openapi/schemas/dto/RentalDto.yaml'
    UserDto:
      $ref: './openapi/schemas/dto/UserDto.yaml'

    # Common schemas
    ValidationErrorResponse:
      $ref: './openapi/schemas/common/ValidationErrorResponse.yaml'
    ProblemDetail:
      $ref: './openapi/schemas/common/ProblemDetail.yaml'