openapi: 3.0.2
info:
  title: Rental OC API
  description: API to manage rental locations and user authentication
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: Authentication
    description: Operations related to user authentication and registration

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: New user registration
      description: Create a new user account with name, email, and password.
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  name: "Required field"
                  email: "Required field / Invalid format / Email already used"
                  password: "Required field"
  /auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticate a user with email and password.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  email: "Required field / Invalid format"
                  password: "Required field"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

components:
  schemas:

    RegisterRequest:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
          description: "User's full name"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
          description: "User's unique email address"
        password:
          type: string
          example: "Password123!"
          description: "User's password"
      required:
        - name
        - email
        - password
      example:
        name: "John Doe"
        email: "john.doe@example"
        password: "Password123!"

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "example@email.com"
        password:
          type: string
          example: "Password123!"
      required:
        - email
        - password
      example:
        email: "example@email.com"
        password: "Password123!"

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: "JWT token for authentication"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      example:
        token: "jwt"

    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
          example: "https://example.com/probs/invalid-credentials"
          description: "A URI reference of the problem type"
        title:
          type: string
          example: "Invalid Credentials"
          description: "The problem title"
        status:
          type: integer
          example: 401
          description: "HTTP status code for the problem"
        detail:
            type: string
            example: "Invalid Credentials"
            description: "The problem detail"
        instance:
            type: string
            format: uri
            example: "/api/auth/login"
            description: "The problem instance request path"
        timestamp:
            type: string
            format: date-time
            example: "2023-10-01T12:00:00Z"
            description: "The time at which the problem occurred"

